// Generated by CoffeeScript 1.6.3
var app, express, http, metric_get, metrics, stylus;

http = require('http');

stylus = require('stylus');

express = require('express');

metrics = require('./metrics');

app = express();

app.set('views', __dirname + '/../views');

app.set('view engine', 'jade');

app.use(express.bodyParser());

app.use(express.methodOverride());

app.use(express.cookieParser('your secret here'));

app.use(express.session());

app.use(app.router);

app.use(stylus.middleware("" + __dirname + "/../public"));

app.use(express["static"]("" + __dirname + "/../public"));

app.use(express.errorHandler({
  showStack: true,
  dumpExceptions: true
}));

app.get('/', function(req, res) {
  return res.render('index', {
    title: 'Metrics'
  });
});

metric_get = function(req, res, next) {
  return metrics.get(req.params.id, function(err, values) {
    if (err) {
      return next(err);
    }
    return res.json({
      id: req.params.id,
      values: values
    });
  });
};

app.get('/metric/:id.json', metric_get);

app.get('/metric?metric=:id', metric_get);

app.post('/metric/:id.json', function(req, res, next) {
  var values;
  values = JSON.parse(req.body);
  return metrics.save(req.params.id, values, function(err) {
    if (err) {
      return next(err);
    }
    return res.json({
      status: 'OK'
    });
  });
});

app["delete"]('/metric/:id.json', function(req, res, next) {
  return metrics.remove(req.params.id, function(err) {
    if (err) {
      return next(err);
    }
    return res.json({
      status: 'OK'
    });
  });
});

http.createServer(app).listen(1234, function() {
  return console.log('http://localhost:1234');
});
