// Generated by CoffeeScript 1.6.3
var db;

db = require('./db')("" + __dirname + "/../db/test");

module.exports = {
  /*
  `get(id, [options], callback)`
  ----------------------------
  Return an array of metrics.
  
  Parameters
  `id`        Metric id as integer
  `callback`  Contains an err as first argument 
              if any
  
  Options
  `start`     Timestamp
  `end`       Timestamp
  `timestamp` Step between each metrics 
              in milliseconds
  */

  get: function(id, options, callback) {
    if (arguments.length === 2) {
      callback = options;
    }
    return setImmediate(function() {
      return callback(null, [
        {
          timestamp: (new Date('2013-11-04 14:00 UTC')).getTime(),
          value: 1234
        }, {
          timestamp: (new Date('2013-11-04 14:10 UTC')).getTime(),
          value: 5678
        }
      ]);
    });
  },
  /*
  `save(id, metrics, callback)`
  ----------------------------
  
  Parameters
  `id`       Metric id as integer
  `metrics`  Array with timestamp as keys 
             and integer as values
  `callback` Contains an err as first argument 
             if any
  */

  save: function(id, metrics, callback) {
    var metric, timestamp, value, ws, _i, _len;
    ws = db.createWriteStream();
    ws.on('error', function(err) {
      return callback(err);
    });
    ws.on('close', function() {
      return callback();
    });
    for (_i = 0, _len = metrics.length; _i < _len; _i++) {
      metric = metrics[_i];
      timestamp = metric.timestamp, value = metric.value;
      ws.write({
        key: "metric:" + id + ":" + timestamp,
        value: value
      });
    }
    return ws.end();
  }
};
